package handler

import (
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/rand"
	"crypto/sha256"
	"encoding/base64"
	"testing"
	"time"
)

func TestStepUpP256SignatureContract(t *testing.T) {
	privateKey, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		t.Fatal(err)
	}
	publicKeyBytes, err := privateKey.PublicKey.Bytes()
	if err != nil {
		t.Fatal(err)
	}
	encoded := base64.RawURLEncoding.EncodeToString(publicKeyBytes)
	if err := validateP256PublicKey(encoded); err != nil {
		t.Fatal(err)
	}
	publicKey, err := decodeP256PublicKey(encoded)
	if err != nil {
		t.Fatal(err)
	}
	expires := time.Date(2026, 8, 7, 12, 30, 0, 123, time.UTC)
	payload := stepUpPayload("challenge-1", "nonce-1", "exec", "atlas", expires)
	digest := sha256.Sum256([]byte(payload))
	signature, err := ecdsa.SignASN1(rand.Reader, privateKey, digest[:])
	if err != nil {
		t.Fatal(err)
	}
	if !ecdsa.VerifyASN1(publicKey, digest[:], signature) {
		t.Fatal("signature generated by a native client must verify against the enrolled public key")
	}
	if got := stepUpPayload("challenge-1", "nonce-1", "exec", "atlas", expires); got != payload {
		t.Fatal("step-up payload must be deterministic")
	}
}

func TestNormalizeEnrollmentCodeIgnoresDisplayFormatting(t *testing.T) {
	if normalizeCode(" abcd-efgh ") != normalizeCode("ABCDEFGH") {
		t.Fatal("display hyphen and casing should not affect enrollment lookup")
	}
}

func TestEnrollmentApprovalCannotAddScope(t *testing.T) {
	requested := []string{ScopeAPIRead, ScopeEventsRead}
	if !containsScope(requested, ScopeEventsRead) {
		t.Fatal("requested scope should be recognized")
	}
	if containsScope(requested, ScopeAppsExec) {
		t.Fatal("approval must not add an unrequested scope")
	}
}
