package controlrecovery

import (
	"crypto/ed25519"
	"encoding/json"
	"os"
	"strings"
	"testing"
	"time"

	"norn/v2/api/model"
)

// The vectors in testdata are generated by the handler's real producers and
// pinned by handler/recovery_vectors_test.go. These tests prove the recovery
// verifier's independent implementation accepts exactly that output.

type qualificationVector struct {
	PublicKey string          `json:"publicKey"`
	Receipt   json.RawMessage `json:"receipt"`
}

type auditVector struct {
	Key   string `json:"key"`
	Event struct {
		ID               string    `json:"id"`
		RequestID        string    `json:"requestId"`
		PrincipalSubject string    `json:"principalSubject"`
		TokenID          string    `json:"tokenId"`
		DeviceID         string    `json:"deviceId"`
		KeyID            string    `json:"keyId"`
		Scopes           []string  `json:"scopes"`
		Method           string    `json:"method"`
		Path             string    `json:"path"`
		ClientIP         string    `json:"clientIp"`
		UserAgent        string    `json:"userAgent"`
		Status           int       `json:"status"`
		Outcome          string    `json:"outcome"`
		StartedAt        time.Time `json:"startedAt"`
		FinishedAt       time.Time `json:"finishedAt"`
		DurationMs       int64     `json:"durationMs"`
	} `json:"event"`
	Digest   string `json:"digest"`
	Incident struct {
		ID             string    `json:"id"`
		AuditEventID   string    `json:"auditEventId"`
		ReasonCode     string    `json:"reasonCode"`
		Explanation    string    `json:"explanation"`
		AcknowledgedBy string    `json:"acknowledgedBy"`
		AcknowledgedAt time.Time `json:"acknowledgedAt"`
		KeyID          string    `json:"keyId"`
	} `json:"incident"`
	IncidentDigest string `json:"incidentDigest"`
}

func loadQualificationVector(t *testing.T) (model.ReleaseQualification, []byte, ed25519.PublicKey) {
	t.Helper()
	encoded, err := os.ReadFile("testdata/release-qualification-v2.json")
	if err != nil {
		t.Fatal(err)
	}
	var vector qualificationVector
	if err := json.Unmarshal(encoded, &vector); err != nil {
		t.Fatal(err)
	}
	public, err := ParseManifestPublicKey([]byte(vector.PublicKey))
	if err != nil {
		t.Fatal(err)
	}
	var receipt model.ReleaseQualification
	if err := decodeExactJSON(vector.Receipt, &receipt); err != nil {
		t.Fatal(err)
	}
	return receipt, vector.Receipt, public
}

func loadAuditVector(t *testing.T) auditVector {
	t.Helper()
	encoded, err := os.ReadFile("testdata/mutation-audit-v1.json")
	if err != nil {
		t.Fatal(err)
	}
	var vector auditVector
	if err := json.Unmarshal(encoded, &vector); err != nil {
		t.Fatal(err)
	}
	return vector
}

func TestQualificationVerifierAcceptsProducerKnownVectorAndRejectsTampering(t *testing.T) {
	receipt, _, public := loadQualificationVector(t)
	trusted := map[string]ed25519.PublicKey{manifestKeyID(public): public}
	if err := verifyQualificationReceipt(receipt, trusted); err != nil {
		t.Fatalf("producer vector rejected: %v", err)
	}
	if receipt.KeyID != manifestKeyID(public) {
		t.Fatalf("producer key ID %q differs from recovery key ID %q", receipt.KeyID, manifestKeyID(public))
	}
	if err := verifyQualificationReceipt(receipt, map[string]ed25519.PublicKey{}); err == nil {
		t.Fatal("untrusted qualification key accepted")
	}
	for name, mutate := range map[string]func(*model.ReleaseQualification){
		"app":        func(r *model.ReleaseQualification) { r.App = "other" },
		"source sha": func(r *model.ReleaseQualification) { r.SourceSHA = strings.Repeat("d", 40) },
		"artifact": func(r *model.ReleaseQualification) {
			r.Artifact = "registry.example.test/demo@sha256:" + strings.Repeat("f", 64)
		},
		"deployment":         func(r *model.ReleaseQualification) { r.DeploymentID = "11111111-1111-4111-8111-111111111111" },
		"id":                 func(r *model.ReleaseQualification) { r.ID = "22222222-2222-4222-8222-222222222222" },
		"issued":             func(r *model.ReleaseQualification) { r.IssuedAt = r.IssuedAt.Add(time.Second) },
		"expires":            func(r *model.ReleaseQualification) { r.ExpiresAt = r.ExpiresAt.Add(time.Hour) },
		"candidate run":      func(r *model.ReleaseQualification) { r.Candidate.RunID = "304" },
		"candidate repo":     func(r *model.ReleaseQualification) { r.Candidate.Repository = "attacker/demo" },
		"candidate signer":   func(r *model.ReleaseQualification) { r.Candidate.SignerWorkflowRef = "" },
		"candidate material": func(r *model.ReleaseQualification) { r.Candidate.Attestation.MaterialSHA = strings.Repeat("d", 40) },
		"environment":        func(r *model.ReleaseQualification) { r.Environment = "production" },
		"schema":             func(r *model.ReleaseQualification) { r.SchemaVersion = "norn.release-qualification/v1" },
		"display key":        func(r *model.ReleaseQualification) { r.KeyID = "ed25519:other" },
		"display signature":  func(r *model.ReleaseQualification) { r.Signature = r.Signature[:len(r.Signature)-2] + "AA" },
		"payload type":       func(r *model.ReleaseQualification) { r.DSSE.PayloadType = "application/json" },
		"second signature": func(r *model.ReleaseQualification) {
			r.DSSE.Signatures = append(r.DSSE.Signatures, r.DSSE.Signatures[0])
		},
		"mutable image": func(r *model.ReleaseQualification) { r.Artifact = "registry.example.test/demo:latest" },
		"short sha":     func(r *model.ReleaseQualification) { r.SourceSHA = "0123456" },
		"subject digest only": func(r *model.ReleaseQualification) {
			r.Candidate.Attestation.SubjectDigest = "sha256:" + strings.Repeat("f", 64)
		},
	} {
		t.Run(name, func(t *testing.T) {
			tampered := receipt
			tampered.Candidate = receipt.Candidate
			tampered.DSSE.Signatures = append([]model.DSSESignature(nil), receipt.DSSE.Signatures...)
			mutate(&tampered)
			if err := verifyQualificationReceipt(tampered, trusted); err == nil {
				t.Fatal("tampered qualification verified")
			}
		})
	}
}

func TestAuditSignerMatchesProducerKnownVector(t *testing.T) {
	vector := loadAuditVector(t)
	finished := vector.Event.FinishedAt
	record := auditRecord{
		ID: vector.Event.ID, RequestID: vector.Event.RequestID, PrincipalSubject: vector.Event.PrincipalSubject, TokenID: vector.Event.TokenID,
		DeviceID: vector.Event.DeviceID, Method: vector.Event.Method, Path: vector.Event.Path, ClientIP: vector.Event.ClientIP, UserAgent: vector.Event.UserAgent,
		Scopes: vector.Event.Scopes, Status: vector.Event.Status, Outcome: vector.Event.Outcome, StartedAt: vector.Event.StartedAt, FinishedAt: &finished,
		DurationMs: vector.Event.DurationMs, KeyID: vector.Event.KeyID,
	}
	key := []byte(vector.Key)
	if hmacKeyID(key) != vector.Event.KeyID {
		t.Fatalf("recovery HMAC key ID %s differs from producer %s", hmacKeyID(key), vector.Event.KeyID)
	}
	if got := signAudit(key, record); got != vector.Digest {
		t.Fatalf("recovery audit digest %s differs from producer %s", got, vector.Digest)
	}
	incident := vector.Incident
	if got := signAuditIncident(key, incident.ID, incident.AuditEventID, incident.ReasonCode, incident.Explanation, incident.AcknowledgedBy, incident.KeyID, incident.AcknowledgedAt); got != vector.IncidentDigest {
		t.Fatalf("recovery incident digest %s differs from producer %s", got, vector.IncidentDigest)
	}
	record.Status = 500
	if signAudit(key, record) == vector.Digest {
		t.Fatal("tampered audit status kept producer digest")
	}
}
